/**
 * Seed data for job discovery (ADR-006: seeded jobs for dev, licensed APIs later).
 *
 * Jobs are generated by crossing role archetypes with companies and locations
 * rather than hand-writing each posting, so the set stays varied enough to
 * exercise search ranking, filters, and facets without becoming unmaintainable.
 *
 * Re-runnable: everything upserts on a stable slug.
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({ log: ['error'] });

type Seniority = 'intern' | 'junior' | 'mid' | 'senior' | 'lead' | 'principal';

interface CompanySeed {
  name: string;
  slug: string;
  industry: string;
  size: string;
  location: string;
  websiteUrl: string;
  about: string;
}

interface RoleTemplate {
  key: string;
  title: string;
  family: string;
  skills: string[];
  summary: string;
  responsibilities: string[];
  requirements: string[];
  /** Mid-level base salary in USD; other seniorities scale from this. */
  baseSalary: number;
  seniorities: Seniority[];
}

const COMPANIES: CompanySeed[] = [
  {
    name: 'Northwind Systems',
    slug: 'northwind-systems',
    industry: 'Cloud Infrastructure',
    size: '501-1000',
    location: 'Austin, TX, United States',
    websiteUrl: 'https://example.com/northwind',
    about:
      'Northwind Systems builds managed Kubernetes and observability tooling for mid-market engineering teams. We run a large multi-region platform and care deeply about operational excellence.',
  },
  {
    name: 'Halcyon Health',
    slug: 'halcyon-health',
    industry: 'Digital Health',
    size: '201-500',
    location: 'Boston, MA, United States',
    websiteUrl: 'https://example.com/halcyon',
    about:
      'Halcyon Health connects patients with care teams through a HIPAA-compliant platform used by more than four hundred clinics across North America.',
  },
  {
    name: 'Meridian Pay',
    slug: 'meridian-pay',
    industry: 'Fintech',
    size: '1001-5000',
    location: 'London, United Kingdom',
    websiteUrl: 'https://example.com/meridian',
    about:
      'Meridian Pay processes cross-border payments for marketplaces and platforms, moving billions annually across forty currencies.',
  },
  {
    name: 'Lumen Analytics',
    slug: 'lumen-analytics',
    industry: 'Data & Analytics',
    size: '51-200',
    location: 'Berlin, Germany',
    websiteUrl: 'https://example.com/lumen',
    about:
      'Lumen Analytics gives product teams a warehouse-native analytics layer, so metrics live next to the data instead of in a separate silo.',
  },
  {
    name: 'Foundry Labs',
    slug: 'foundry-labs',
    industry: 'Developer Tools',
    size: '11-50',
    location: 'Remote, Worldwide',
    websiteUrl: 'https://example.com/foundry',
    about:
      'Foundry Labs is a small, fully distributed team building CI and release tooling for open-source maintainers.',
  },
  {
    name: 'Verdant Retail Group',
    slug: 'verdant-retail-group',
    industry: 'E-commerce',
    size: '1001-5000',
    location: 'Toronto, ON, Canada',
    websiteUrl: 'https://example.com/verdant',
    about:
      'Verdant Retail Group runs a portfolio of sustainable consumer brands with a shared commerce and fulfilment platform.',
  },
  {
    name: 'Atlas Mobility',
    slug: 'atlas-mobility',
    industry: 'Transportation',
    size: '501-1000',
    location: 'Amsterdam, Netherlands',
    websiteUrl: 'https://example.com/atlas',
    about:
      'Atlas Mobility operates fleet routing and telematics software for logistics operators across the European Union.',
  },
  {
    name: 'Cobalt Security',
    slug: 'cobalt-security',
    industry: 'Cybersecurity',
    size: '201-500',
    location: 'Singapore',
    websiteUrl: 'https://example.com/cobalt',
    about:
      'Cobalt Security provides continuous cloud posture management and threat detection for regulated industries in APAC.',
  },
  {
    name: 'Cadence Learning',
    slug: 'cadence-learning',
    industry: 'Education Technology',
    size: '51-200',
    location: 'Remote, Europe',
    websiteUrl: 'https://example.com/cadence',
    about:
      'Cadence Learning builds adaptive assessment tools used by universities and professional certification bodies.',
  },
  {
    name: 'Orbital Media',
    slug: 'orbital-media',
    industry: 'Media & Streaming',
    size: '201-500',
    location: 'Los Angeles, CA, United States',
    websiteUrl: 'https://example.com/orbital',
    about:
      'Orbital Media runs a streaming platform for independent film, handling encoding, delivery, and rights management in house.',
  },
];

const ROLES: RoleTemplate[] = [
  {
    key: 'backend-engineer',
    title: 'Backend Engineer',
    family: 'Engineering',
    skills: ['Python', 'PostgreSQL', 'REST APIs', 'Docker', 'AWS', 'Redis'],
    summary:
      'Design, build, and operate the services that power our core product. You will own features end to end, from schema design through rollout and the metrics that tell us it worked.',
    responsibilities: [
      'Design and ship backend services and APIs used by web and mobile clients',
      'Model data and evolve database schemas with safe, reversible migrations',
      'Instrument services with logging, metrics, and tracing so failures are diagnosable',
      'Review peers\u2019 changes and help keep the codebase coherent as it grows',
    ],
    requirements: [
      'Production experience with a server-side language such as Python, Go, or Java',
      'Comfortable designing relational schemas and writing non-trivial SQL',
      'Familiarity with containerised deployment and a major cloud provider',
      'Track record of owning services in production, including on-call',
    ],
    baseSalary: 135000,
    seniorities: ['junior', 'mid', 'senior', 'lead'],
  },
  {
    key: 'frontend-engineer',
    title: 'Frontend Engineer',
    family: 'Engineering',
    skills: ['TypeScript', 'React', 'Next.js', 'CSS', 'Accessibility', 'Testing Library'],
    summary:
      'Build interfaces that stay fast and legible as the product grows. We care about accessibility and perceived performance as much as we care about what the design looks like in Figma.',
    responsibilities: [
      'Build and maintain product surfaces in React and TypeScript',
      'Work with designers to turn flows into accessible, responsive interfaces',
      'Keep bundle size and interaction latency within agreed budgets',
      'Extend the shared component library and its documentation',
    ],
    requirements: [
      'Strong TypeScript and modern React, including hooks and server components',
      'Practical understanding of WCAG accessibility requirements',
      'Experience with component and end-to-end testing',
      'An eye for detail in spacing, typography, and motion',
    ],
    baseSalary: 128000,
    seniorities: ['junior', 'mid', 'senior'],
  },
  {
    key: 'fullstack-engineer',
    title: 'Full Stack Engineer',
    family: 'Engineering',
    skills: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'GraphQL', 'AWS'],
    summary:
      'Work across the stack on features that touch the database, the API, and the interface. This role suits someone who would rather follow one problem all the way through than specialise narrowly.',
    responsibilities: [
      'Deliver features spanning database, API, and user interface',
      'Break large pieces of work into increments that ship independently',
      'Partner with product and design from problem framing through launch',
      'Improve developer tooling and reduce friction in the release process',
    ],
    requirements: [
      'Experience shipping full-stack features in a TypeScript codebase',
      'Working knowledge of relational databases and API design',
      'Comfortable with ambiguity and defining scope alongside product',
      'Clear written communication for design documents and reviews',
    ],
    baseSalary: 140000,
    seniorities: ['mid', 'senior', 'lead'],
  },
  {
    key: 'data-engineer',
    title: 'Data Engineer',
    family: 'Data',
    skills: ['Python', 'SQL', 'dbt', 'Airflow', 'Snowflake', 'Kafka'],
    summary:
      'Build the pipelines and models the rest of the company relies on. You will own data quality and freshness, not just the orchestration graph.',
    responsibilities: [
      'Build batch and streaming pipelines feeding the analytics warehouse',
      'Model curated datasets in dbt with tests and documentation',
      'Monitor freshness and quality, and resolve upstream issues at the source',
      'Partner with analysts and product teams on new data products',
    ],
    requirements: [
      'Strong SQL and Python for data manipulation',
      'Experience with an orchestrator such as Airflow, Dagster, or Prefect',
      'Familiarity with dimensional modelling and warehouse design',
      'Understanding of streaming systems and event-driven architecture',
    ],
    baseSalary: 138000,
    seniorities: ['mid', 'senior', 'lead'],
  },
  {
    key: 'machine-learning-engineer',
    title: 'Machine Learning Engineer',
    family: 'Data',
    skills: ['Python', 'PyTorch', 'MLOps', 'Kubernetes', 'Feature Engineering', 'LLMs'],
    summary:
      'Take models from notebook to production and keep them healthy once they are there. Much of the work is evaluation, serving, and monitoring rather than novel modelling.',
    responsibilities: [
      'Train, evaluate, and deploy models against clearly defined offline metrics',
      'Build serving infrastructure that meets latency and cost targets',
      'Design evaluation sets and monitor for drift once models are live',
      'Work with product teams to frame problems in terms models can actually solve',
    ],
    requirements: [
      'Experience deploying machine learning models to production',
      'Fluency in Python and a deep learning framework such as PyTorch',
      'Understanding of evaluation methodology and its failure modes',
      'Exposure to retrieval, embeddings, or large language model applications',
    ],
    baseSalary: 158000,
    seniorities: ['mid', 'senior', 'principal'],
  },
  {
    key: 'devops-engineer',
    title: 'Site Reliability Engineer',
    family: 'Infrastructure',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'Prometheus', 'CI/CD', 'Linux'],
    summary:
      'Keep the platform available and make it cheaper and calmer to operate. You will be as involved in incident review and capacity planning as in writing automation.',
    responsibilities: [
      'Operate and scale Kubernetes clusters across multiple regions',
      'Codify infrastructure with Terraform and keep environments reproducible',
      'Improve observability and reduce alert noise for on-call engineers',
      'Lead incident response and drive follow-up actions to completion',
    ],
    requirements: [
      'Deep Linux and networking fundamentals',
      'Production Kubernetes experience at meaningful scale',
      'Infrastructure-as-code discipline, ideally with Terraform',
      'Calm, methodical approach to incidents and postmortems',
    ],
    baseSalary: 148000,
    seniorities: ['mid', 'senior', 'lead'],
  },
  {
    key: 'mobile-engineer',
    title: 'Mobile Engineer',
    family: 'Engineering',
    skills: ['React Native', 'Swift', 'Kotlin', 'iOS', 'Android', 'Mobile Testing'],
    summary:
      'Own the mobile experience end to end, from offline behaviour and release trains to the details that make an app feel native on each platform.',
    responsibilities: [
      'Build and ship features across iOS and Android',
      'Manage release trains, staged rollouts, and store submissions',
      'Profile and fix performance, battery, and memory problems',
      'Handle offline state and unreliable connectivity gracefully',
    ],
    requirements: [
      'Shipped and maintained apps on the App Store or Play Store',
      'Comfortable with at least one native platform alongside cross-platform work',
      'Understanding of mobile-specific testing and release practices',
      'Attention to platform interaction conventions',
    ],
    baseSalary: 132000,
    seniorities: ['mid', 'senior'],
  },
  {
    key: 'security-engineer',
    title: 'Security Engineer',
    family: 'Security',
    skills: ['Threat Modeling', 'AppSec', 'Cloud Security', 'Python', 'SIEM', 'Incident Response'],
    summary:
      'Reduce risk in a way engineering teams can actually adopt. The role balances proactive design review with detection engineering and response.',
    responsibilities: [
      'Run threat models and security reviews for new systems',
      'Build detections and tune alerting to keep signal high',
      'Lead response for security incidents and drive remediation',
      'Improve secure defaults in shared libraries and infrastructure',
    ],
    requirements: [
      'Background in application or cloud security engineering',
      'Ability to read and write code, not just review findings',
      'Familiarity with a major compliance regime such as SOC 2 or ISO 27001',
      'Judgement about which risks matter and which do not',
    ],
    baseSalary: 150000,
    seniorities: ['mid', 'senior', 'lead'],
  },
  {
    key: 'product-designer',
    title: 'Product Designer',
    family: 'Design',
    skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping', 'Accessibility'],
    summary:
      'Own the design of a product area from research through delivery, working close enough to engineering that what ships resembles what was designed.',
    responsibilities: [
      'Lead design for a product area, from discovery through launch',
      'Run research and usability sessions, and act on what they surface',
      'Contribute to and maintain the shared design system',
      'Pair with engineers during build to resolve details in context',
    ],
    requirements: [
      'Portfolio showing shipped product work and the reasoning behind it',
      'Fluency in Figma and modern prototyping practice',
      'Experience contributing to a design system',
      'Comfort presenting and defending decisions to stakeholders',
    ],
    baseSalary: 125000,
    seniorities: ['mid', 'senior', 'lead'],
  },
  {
    key: 'product-manager',
    title: 'Product Manager',
    family: 'Product',
    skills: ['Product Strategy', 'Roadmapping', 'SQL', 'A/B Testing', 'Stakeholder Management'],
    summary:
      'Decide what the team builds next and why. You will be accountable for outcomes rather than output, and expected to say no often.',
    responsibilities: [
      'Own strategy and roadmap for a product area',
      'Turn customer and data signals into a prioritised, defensible plan',
      'Define success metrics up front and report against them honestly',
      'Keep engineering, design, and go-to-market aligned on the same goal',
    ],
    requirements: [
      'Experience owning a product area at a software company',
      'Comfortable querying data yourself to answer your own questions',
      'Strong written communication, especially for strategy documents',
      'Track record of shipping and then measuring',
    ],
    baseSalary: 142000,
    seniorities: ['mid', 'senior', 'principal'],
  },
  {
    key: 'data-analyst',
    title: 'Data Analyst',
    family: 'Data',
    skills: ['SQL', 'Python', 'Tableau', 'Statistics', 'Experimentation', 'dbt'],
    summary:
      'Answer the questions that change decisions. You will work close to the business and be expected to push back when a question is the wrong one.',
    responsibilities: [
      'Build dashboards and self-serve models teams actually use',
      'Design and read experiments, including the awkward results',
      'Investigate anomalies and explain them in plain language',
      'Improve data definitions so teams stop disagreeing about numbers',
    ],
    requirements: [
      'Advanced SQL and a scripting language for analysis',
      'Solid grounding in statistics and experimental design',
      'Experience with a BI tool such as Tableau, Looker, or Metabase',
      'Ability to explain analysis to non-technical stakeholders',
    ],
    baseSalary: 105000,
    seniorities: ['junior', 'mid', 'senior'],
  },
  {
    key: 'qa-engineer',
    title: 'QA Automation Engineer',
    family: 'Engineering',
    skills: ['Playwright', 'TypeScript', 'CI/CD', 'API Testing', 'Test Strategy'],
    summary:
      'Build the automated testing that lets the team ship daily without fear, and shape the strategy for what is worth testing at all.',
    responsibilities: [
      'Build and maintain end-to-end and integration test suites',
      'Keep the pipeline fast and free of flaky tests',
      'Define test strategy alongside engineering leads',
      'Investigate escaped defects and close the gaps that let them through',
    ],
    requirements: [
      'Experience with a modern automation framework such as Playwright or Cypress',
      'Comfortable writing TypeScript or Python test code',
      'Understanding of CI pipelines and test parallelisation',
      'Pragmatism about coverage versus maintenance cost',
    ],
    baseSalary: 112000,
    seniorities: ['junior', 'mid', 'senior'],
  },
];

const LOCATIONS = [
  { location: 'Remote, Worldwide', city: null, country: 'Remote', workMode: 'remote' },
  {
    location: 'Austin, TX, United States',
    city: 'Austin',
    country: 'United States',
    workMode: 'hybrid',
  },
  {
    location: 'London, United Kingdom',
    city: 'London',
    country: 'United Kingdom',
    workMode: 'hybrid',
  },
  { location: 'Berlin, Germany', city: 'Berlin', country: 'Germany', workMode: 'on-site' },
  { location: 'Toronto, ON, Canada', city: 'Toronto', country: 'Canada', workMode: 'hybrid' },
  { location: 'Remote, Europe', city: null, country: 'Remote', workMode: 'remote' },
  { location: 'Singapore', city: 'Singapore', country: 'Singapore', workMode: 'on-site' },
  {
    location: 'New York, NY, United States',
    city: 'New York',
    country: 'United States',
    workMode: 'hybrid',
  },
];

const SENIORITY_PREFIX: Record<Seniority, string> = {
  intern: 'Intern',
  junior: 'Junior',
  mid: '',
  senior: 'Senior',
  lead: 'Lead',
  principal: 'Principal',
};

const SENIORITY_MULTIPLIER: Record<Seniority, number> = {
  intern: 0.35,
  junior: 0.72,
  mid: 1,
  senior: 1.3,
  lead: 1.55,
  principal: 1.8,
};

const SENIORITY_YEARS: Record<Seniority, string> = {
  intern: 'currently studying toward a relevant degree',
  junior: 'around 1-2 years of professional experience',
  mid: '3-5 years of professional experience',
  senior: '5-8 years of professional experience',
  lead: '8+ years of experience including technical leadership',
  principal: '10+ years of experience setting technical direction',
};

const EMPLOYMENT_TYPES = ['full-time', 'full-time', 'full-time', 'contract', 'part-time'];

const BENEFITS = [
  'Private health, dental, and vision cover',
  'Annual learning budget and conference allowance',
  'Home office stipend',
  'Flexible working hours across time zones',
  'Equity participation',
  'Paid parental leave',
  'Four weeks paid holiday plus public holidays',
];

/** Deterministic pseudo-random so re-seeding produces identical data. */
function hash(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return Math.abs(h);
}

function pick<T>(items: T[], key: string, offset = 0): T {
  return items[(hash(key) + offset) % items.length];
}

function roundTo(value: number, step: number): number {
  return Math.round(value / step) * step;
}

function buildDescription(role: RoleTemplate, company: CompanySeed, seniority: Seniority): string {
  return [
    `${company.name} is hiring a ${SENIORITY_PREFIX[seniority] ? `${SENIORITY_PREFIX[seniority]} ` : ''}${role.title} to join our ${role.family} team.`,
    '',
    role.summary,
    '',
    `About ${company.name}: ${company.about}`,
    '',
    `We are looking for someone with ${SENIORITY_YEARS[seniority]}. We review every application ourselves and aim to respond within a week.`,
  ].join('\n');
}

async function main() {
  const companies = new Map<string, string>();

  for (const company of COMPANIES) {
    const record = await prisma.company.upsert({
      where: { slug: company.slug },
      update: {
        name: company.name,
        industry: company.industry,
        size: company.size,
        location: company.location,
        websiteUrl: company.websiteUrl,
        about: company.about,
      },
      create: company,
    });
    companies.set(company.slug, record.id);
  }

  console.log(`seeded ${companies.size} companies`);

  let created = 0;
  let updated = 0;
  const now = Date.now();

  for (const role of ROLES) {
    for (const seniority of role.seniorities) {
      // Spread each role across a few companies so filters return varied results.
      const companyCount = seniority === 'mid' || seniority === 'senior' ? 2 : 1;

      for (let n = 0; n < companyCount; n += 1) {
        const company = pick(COMPANIES, `${role.key}:${seniority}`, n * 3);
        const place = pick(LOCATIONS, `${role.key}:${seniority}:${company.slug}`, n);
        const employmentType = pick(EMPLOYMENT_TYPES, `${role.key}:${company.slug}:${seniority}`);

        const prefix = SENIORITY_PREFIX[seniority];
        const title = prefix ? `${prefix} ${role.title}` : role.title;
        const slug = `${company.slug}-${seniority}-${role.key}-${n}`;

        const midpoint = role.baseSalary * SENIORITY_MULTIPLIER[seniority];
        const salaryMin = roundTo(midpoint * 0.9, 1000);
        const salaryMax = roundTo(midpoint * 1.2, 1000);

        // Stagger posting dates over the last six weeks so "recent" sorting is meaningful.
        const daysAgo = hash(slug) % 42;
        const postedAt = new Date(now - daysAgo * 24 * 60 * 60 * 1000);

        const benefitCount = 3 + (hash(slug) % 3);
        const benefits = BENEFITS.slice(0, benefitCount);

        const data = {
          companyId: companies.get(company.slug)!,
          title,
          description: buildDescription(role, company, seniority),
          responsibilities: role.responsibilities,
          requirements: [...role.requirements, `We expect ${SENIORITY_YEARS[seniority]}.`],
          benefits,
          skills: role.skills,
          employmentType,
          workMode: place.workMode,
          seniority,
          location: place.location,
          city: place.city,
          country: place.country,
          salaryMin,
          salaryMax,
          salaryCurrency: 'USD',
          salaryPeriod: 'year',
          source: 'seed',
          externalId: slug,
          applyUrl: `${company.websiteUrl}/careers/${slug}`,
          postedAt,
          isActive: true,
        };

        const existing = await prisma.job.findUnique({ where: { slug }, select: { id: true } });

        if (existing) {
          await prisma.job.update({ where: { slug }, data });
          updated += 1;
        } else {
          await prisma.job.create({ data: { ...data, slug } });
          created += 1;
        }
      }
    }
  }

  console.log(`seeded jobs: ${created} created, ${updated} updated`);

  // Content changed, so any existing embeddings are stale.
  const reset = await prisma.job.updateMany({
    where: { source: 'seed' },
    data: { embeddingStatus: 'idle', embeddingError: null },
  });
  console.log(`marked ${reset.count} jobs for re-embedding`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
